## here i set set host network for fail2ban
version: '2'

services: 
 ## tinyproxy        
        
    tinyproxy:  
      build:
        context: ./tinyproxy
      volumes:
        - ./tinyproxy/tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf
     
## stunnel conf

    stunnel:  
      build:
        context: ./stunnel
      depends_on:
        - tinyproxy
      volumes:
        - ./stunnel/stunnel.conf:/etc/stunnel/stunnel.conf
        - ./stunnel/certs/:/etc/ssl/mycerts/
        
    stunnel-client:  
      build:
        context: ./stunnel-client
      ports:
        - "127.0.0.1:8081:8081"
      depends_on:
        - stunnel
      volumes:
        - ./stunnel-client/stunnel.conf:/etc/stunnel/stunnel.conf
        - ./stunnel/certs:/etc/ssl/certs        
