## here i set set host network for fail2ban
version: '2'

services: 
 ## tinyproxy        
        
    tinyproxy:  
      build:
        context: ./tinyproxy
      network_mode: host
      volumes:
        - ./tinyproxy/tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf
     
## stunnel conf

    stunnel:  
      build:
        context: ./stunnel
      network_mode: host
      volumes:
        - ./stunnel/stunnel.conf:/etc/stunnel/stunnel.conf
        - ./stunnel/certs/:/etc/ssl/mycerts/
        
    stunnel-client:  
      build:
        context: ./stunnel-client
      network_mode: host
      volumes:
        - ./stunnel-client/stunnel.conf:/etc/stunnel/stunnel.conf
        - ./stunnel/certs:/etc/ssl/certs        
